CSHARP/OENIK_PROG3_2019_2_YGHR5J/MyGame.Web/Models/Monster.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyGame.Web.Models
{
    public class Monster
    {
        [Required]
        [Display(Name = "Mon Id")]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Mon Name")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Mon Element")]
        [Range(1, 8)]
        public int ElementId { get; set; }
        [Required]
        [Display(Name = "Mon Type")]
        public string Type { get; set; }
        [Required]
        [Display(Name = "Mon Hitpoints")]
        public int Hitpoints { get; set; }
        [Required]
        [Display(Name = "Mon Attack")]
        public int Attack { get; set; }
        [Required]
        [Display(Name = "Mon Defense")]
        public int Defense { get; set; }

        public Monster(string monster)
        {
            string[] mon = monster.Trim(' ').Split('-');
            Id = int.Parse(mon[0]);
            Name = mon[1];
            ElementId = int.Parse(mon[2]);
            Type = mon[3];
            Hitpoints = int.Parse(mon[4]);
            Attack = int.Parse(mon[5]);
            Defense = int.Parse(mon[6]);
        }
        public Monster()
        {

        }
    }
}

CSHARP/OENIK_PROG3_2019_2_YGHR5J/MyGame.Web/Models/MonstersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace MyGame.Web.Models
{
    public class MonstersViewModel
    {
        public List<Monster> ListOfMonsters { get; set; }
        public Monster EditedMonster { get; set; }
        public MonstersViewModel()
        {
            ListOfMonsters = new List<Monster>();
        }
    }
}

CSHARP/OENIK_PROG3_2019_2_YGHR5J/MyGame.Web/Controllers/MonstersController.cs
using MyGame.Logic;
using MyGame.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyGame.Web.Controllers
{
    public class MonstersController : Controller
    {
        GameLogic logic;
        MonstersViewModel vm;
        public MonstersController()
        {
            logic = new GameLogic();
            vm = new MonstersViewModel();
            vm.ListOfMonsters = Converter.ConvertMonsters(logic.GetAllMonster());
            vm.EditedMonster = new Monster();
        }
       
        public Monster GetMonster(int id)
        {
            Monster monster = new Monster(logic.GetMonsterById(id));
            return monster;
        }

        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("MonsterIndex", vm);
        }
        public ActionResult Details(int id)
        {
            return View("MonsterDetails", GetMonster(id));
        }
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "edit";
            vm.EditedMonster = GetMonster(id);
            return View("MonsterIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Monster mon, string editAction)
        {
            if (ModelState.IsValid && mon != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    try
                    {
                        logic.AddMonster(mon.Name, mon.ElementId, mon.Type, mon.Hitpoints, mon.Attack, mon.Defense);
                    }
                    catch (Exception)
                    {
                        TempData["editResult"] = "Addition FAIL";
                    }
                }
                else
                {
                    try
                    {
                        logic.UpdateMonster(mon.Id, mon.Name, mon.ElementId, mon.Type, mon.Hitpoints, mon.Attack, mon.Defense);
                    }
                    catch (Exception)
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["editResult"] = "Edit FAIL";
                ViewData["editAction"] = "edit";
                vm.EditedMonster = mon;
                return View("MonsterIndex", vm);
            }
        }


        public ActionResult Delete(int id)
        {
            try
            {
                TempData["editResult"] = "Delete OK";
                logic.DeleteMonster(id);
            }
            catch (Exception)
            {
                TempData["editResult"] = "Delete FAIL";
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

CSHARP/OENIK_PROG3_2019_2_YGHR5J/MyGame.Web/Views/Monsters/MonsterDetails.cshtml
@model MyGame.Web.Models.Monster

@{
    ViewBag.Title = "MonsterDetails";
}

<h2>Monster Details</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>The ID for the car</td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Type)</td>
        <td>@Html.DisplayFor(m => m.Type)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ElementId)</td>
        <td>@Html.DisplayFor(m => m.ElementId)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Hitpoints)</td>
        <td>@Html.DisplayFor(m => m.Hitpoints)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Attack)</td>
        <td>@Html.DisplayFor(m => m.Attack)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Defense)</td>
        <td>@Html.DisplayFor(m => m.Defense)</td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_2_YGHR5J/MyGame.Web/Views/Monsters/MonsterEdit.cshtml
@model MyGame.Web.Models.Monster

<h2>Edit a monster</h2>

@using (Html.BeginForm("Edit", "Monsters"))
{

    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.ElementId)</div>
    <div class="editor-field">@Html.EditorFor(m => m.ElementId)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Type)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Type)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Hitpoints)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Hitpoints)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Attack)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Attack)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Defense)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Defense)</div>

    <input type="submit" value="Edit/Add" />
}

CSHARP/OENIK_PROG3_2019_2_YGHR5J/MyGame.Web/Views/Monsters/MonsterIndex.cshtml
@model MyGame.Web.Models.MonstersViewModel
@{
    ViewBag.Title = "MonsterIndex";
}

<h2>Monster Index</h2>
<p style="color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("MonsterEdit", Model.EditedMonster)
@Html.Partial("MonsterList", Model.ListOfMonsters)

CSHARP/OENIK_PROG3_2019_2_YGHR5J/MyGame.Web/Views/Monsters/MonsterList.cshtml
@model IEnumerable<MyGame.Web.Models.Monster>


@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Type)</th>
            <th>Details</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        <tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => item.Name)</td>
                    <td>@Html.DisplayFor(m => item.Type)</td>
                    <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id })</td>
                    <td>@Html.ActionLink("[DELETE]", "Delete", new { id = item.Id })</td>
                    <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
                </tr>
            }
            </tr>
        </table>
    }